In [48]:
list=[] # empty list
list1=[0] #single element list

In [49]:
print(list,id(list),type(list))

[] 1718163260928 <class 'list'>


In [50]:
list.append(1) # adding item in list
print(list)

[1]


In [51]:
list.pop(0) # remove the element of index 0

1

In [52]:
print(list)

[]


In [53]:
list.append(1)
list.append(2)
list.append(3)
list.append(4)
list.append(5)
list.append(6)
list.append(7)
list.append(8)
list.append(9)
list.append(9)

In [54]:
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 9]


In [55]:
list.remove(9) #remove only one 9 from the list

In [56]:
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [69]:
n=input("Enter the list item seperated with only one space:")
list2=n.split()
print(list2)



['1', '0', '5', '2', '5', '8', '8', '8', '88', '8', '8', '5', '5']


In [86]:
size=len(list2)
print(size)

13


In [85]:
for i in range(size):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12


In [87]:
print(list2)

['1', '0', '5', '2', '5', '8', '8', '8', '88', '8', '8', '5', '5']


In [90]:
while list2:
    print(list2.pop())

# for item in list2:
#     print(item)
# list2[:] = []

In [91]:
print(list2)

[]


proble solving questions


In [98]:
def creating_gen(index):  
    months = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']  
    yield months[index]  
    yield months[index+1]  
    yield months[index+2]  
next_month = creating_gen(0)  
print(next(next_month), next(next_month), next(next_month)) 

jan feb mar


Changing a list into a tuple

In [99]:
month = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']  
m_to_list = tuple(month)  # this will chage a list into a tuple
print(m_to_list)  
print(type(m_to_list))  


('jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec')
<class 'tuple'>


# what is numpy array
it is more versatile than the list

In [101]:
# creating an empty array in python

In [102]:
import numpy  
#method 1  
array_1 = numpy.array([])  
print(array_1)  
#method 2  
array_2 = numpy.empty(shape=(3,3))  
print(array_2)  

[]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.94457559e-321]
 [6.23053614e-307 7.56592337e-307 5.33590898e-322]]


In [103]:

a = [4, 6, 8, 3, 1, 7]  
print(a[-3])  
print(a[-5])  
print(a[-1])  

3
6
7
