In [4]:
list=[] # empty list
list1=[0] #single element list

In [5]:
print(list,id(list),type(list))

[] 2404034584320 <class 'list'>


In [6]:
list.append(1) # adding item in list
print(list)

[1]


In [7]:
list.pop(0) # remove the element of index 0

1

In [8]:
print(list)

[]


In [9]:
list.append(1)
list.append(2)
list.append(3)
list.append(4)
list.append(5)
list.append(6)
list.append(7)
list.append(8)
list.append(9)
list.append(9)

In [10]:
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 9]


In [11]:
list.remove(9) #remove only one 9 from the list

In [12]:
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [13]:
n=input("Enter the list item seperated with only one space:")
list2=n.split()
print(list2)



['4', '5', '7', '8', '5', '5', '5']


In [14]:
size=len(list2)
print(size)

7


In [15]:
for i in range(size):
    print(i)


0
1
2
3
4
5
6


In [16]:
print(list2)

['4', '5', '7', '8', '5', '5', '5']


In [17]:
while list2:
    print(list2.pop())

# for item in list2:
#     print(item)
# list2[:] = []

5
5
5
8
7
5
4


In [18]:
print(list2)

[]


proble solving questions


In [19]:
def creating_gen(index):  
    months = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']  
    yield months[index]  
    yield months[index+1]  
    yield months[index+2]  
next_month = creating_gen(0)  
print(next(next_month), next(next_month), next(next_month)) 

jan feb mar


Changing a list into a tuple

In [20]:
month = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']  
m_to_list = tuple(month)  # this will chage a list into a tuple
print(m_to_list)  
print(type(m_to_list))  


('jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec')
<class 'tuple'>


# what is numpy array
it is more versatile than the list

In [21]:
# creating an empty array in python

In [22]:
import numpy  
#method 1  
array_1 = numpy.array([])  
print(array_1)  
#method 2  
array_2 = numpy.empty(shape=(3,3))  
print(array_2)  

[]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.70742408e-321]
 [7.56592337e-307 9.34588060e-307 3.62651150e-317]]


In [23]:

a = [4, 6, 8, 3, 1, 7]  
print(a[-3])  
print(a[-5])  
print(a[-1])  

3
6
7


In [24]:
x=[] #blank list
x1=[1,2,3] # list with 3 element
x2=[4,5,'Apple','Orange'] # mixed element
x3=['Aman','Naman'] # string element

In [25]:
print(x, x1, x2, x3)

[] [1, 2, 3] [4, 5, 'Apple', 'Orange'] ['Aman', 'Naman']


In [26]:
x1 + x2 # adding two list 

[1, 2, 3, 4, 5, 'Apple', 'Orange']

In [27]:
x5 = x1*5
print(x5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [28]:
good_movies=['Pathan', '3 idiots', 'Bahubali', 'Farzi','Kabir Singh']
bad_movies=['Disaster','Birdemic','House of the dead', "son of the mask", 'circus']


In [29]:
all_movies= good_movies + bad_movies
print(all_movies)

['Pathan', '3 idiots', 'Bahubali', 'Farzi', 'Kabir Singh', 'Disaster', 'Birdemic', 'House of the dead', 'son of the mask', 'circus']


In [30]:
all_movies.append('Troll 2')
all_movies.append('The Conjuring')

In [31]:
print(all_movies)

['Pathan', '3 idiots', 'Bahubali', 'Farzi', 'Kabir Singh', 'Disaster', 'Birdemic', 'House of the dead', 'son of the mask', 'circus', 'Troll 2', 'The Conjuring']


In [32]:
print(len(all_movies))

12


In [33]:
all_movies.insert(2,'The Dark Knight')
print(all_movies)

['Pathan', '3 idiots', 'The Dark Knight', 'Bahubali', 'Farzi', 'Kabir Singh', 'Disaster', 'Birdemic', 'House of the dead', 'son of the mask', 'circus', 'Troll 2', 'The Conjuring']


In [34]:
sequels =['Fast & Furious', '2 fast 2 furious', 'Fast & Furious: Tokyo Draft']
all_movies.extend(sequels) # add all items of list 2 in list 1

In [35]:
print(all_movies)

['Pathan', '3 idiots', 'The Dark Knight', 'Bahubali', 'Farzi', 'Kabir Singh', 'Disaster', 'Birdemic', 'House of the dead', 'son of the mask', 'circus', 'Troll 2', 'The Conjuring', 'Fast & Furious', '2 fast 2 furious', 'Fast & Furious: Tokyo Draft']


In [36]:
print(len(all_movies))

16


In [37]:
all_movies.remove("Birdemic")


In [38]:
print(all_movies)

['Pathan', '3 idiots', 'The Dark Knight', 'Bahubali', 'Farzi', 'Kabir Singh', 'Disaster', 'House of the dead', 'son of the mask', 'circus', 'Troll 2', 'The Conjuring', 'Fast & Furious', '2 fast 2 furious', 'Fast & Furious: Tokyo Draft']


In [39]:
all_movies.sort


<function list.sort(*, key=None, reverse=False)>

In [40]:
all_movies[:5] # first five element

['Pathan', '3 idiots', 'The Dark Knight', 'Bahubali', 'Farzi']

In [41]:
all_movies[-5:] # last five element

['Troll 2',
 'The Conjuring',
 'Fast & Furious',
 '2 fast 2 furious',
 'Fast & Furious: Tokyo Draft']

In [42]:
all_movies[3]= 'Bahubali 2 : The Conclusion'
print(all_movies)

['Pathan', '3 idiots', 'The Dark Knight', 'Bahubali 2 : The Conclusion', 'Farzi', 'Kabir Singh', 'Disaster', 'House of the dead', 'son of the mask', 'circus', 'Troll 2', 'The Conjuring', 'Fast & Furious', '2 fast 2 furious', 'Fast & Furious: Tokyo Draft']


In [43]:
all_movies.reverse
print(all_movies)

['Pathan', '3 idiots', 'The Dark Knight', 'Bahubali 2 : The Conclusion', 'Farzi', 'Kabir Singh', 'Disaster', 'House of the dead', 'son of the mask', 'circus', 'Troll 2', 'The Conjuring', 'Fast & Furious', '2 fast 2 furious', 'Fast & Furious: Tokyo Draft']


In [44]:
all_movies.sort()
print(all_movies)

['2 fast 2 furious', '3 idiots', 'Bahubali 2 : The Conclusion', 'Disaster', 'Farzi', 'Fast & Furious', 'Fast & Furious: Tokyo Draft', 'House of the dead', 'Kabir Singh', 'Pathan', 'The Conjuring', 'The Dark Knight', 'Troll 2', 'circus', 'son of the mask']


In [45]:
all_movies.sort(reverse=True)
print(all_movies)

['son of the mask', 'circus', 'Troll 2', 'The Dark Knight', 'The Conjuring', 'Pathan', 'Kabir Singh', 'House of the dead', 'Fast & Furious: Tokyo Draft', 'Fast & Furious', 'Farzi', 'Disaster', 'Bahubali 2 : The Conclusion', '3 idiots', '2 fast 2 furious']


In [46]:
import random as rnd
rnd.shuffle(all_movies)     
print(all_movies)

['Farzi', 'son of the mask', 'Disaster', 'Pathan', 'Fast & Furious', '2 fast 2 furious', 'Kabir Singh', 'House of the dead', '3 idiots', 'Fast & Furious: Tokyo Draft', 'The Conjuring', 'The Dark Knight', 'circus', 'Bahubali 2 : The Conclusion', 'Troll 2']


In [47]:
rnd.choice(all_movies)

'Fast & Furious: Tokyo Draft'

In [48]:
rnd.choices(all_movies, k=2)

['Farzi', 'Fast & Furious']

In [49]:
all_movies.index('3 idiots')

8

In [50]:
all_movies.pop() # remove element from last 

'Troll 2'

In [51]:
all_movies.pop(3) # remove element at that index

'Pathan'

In [52]:
x= [1,2,3,4]
y = x
y[0]=100 # here the changes will happen in both x and y
x[2]= 200
print(x)
print(y)
print(x is y)
print(y is x)

[100, 2, 200, 4]
[100, 2, 200, 4]
True
True


In [53]:
z = x.copy() # this will copy the value of x in z
z.pop()
print(x)
print(z)

[100, 2, 200, 4]
[100, 2, 200]


In [54]:
print(z is x)

False


In [58]:
def even(length): # programm to print sum of even number of a lsit
    list = []
    for i in range(length):
        a=int(input("Enter list items : "))
        list.append(a)
    total= len(list)
    summ = 0
    for j in range(total):
        if list[j] % 2 == 0:
            summ += list[j]
            return summ
        else:
            ok =sum(list)
            return ok
print(even(5))

4
