In [48]:
list=[] # empty list
list1=[0] #single element list

In [49]:
print(list,id(list),type(list))

[] 1718163260928 <class 'list'>


In [50]:
list.append(1) # adding item in list
print(list)

[1]


In [51]:
list.pop(0) # remove the element of index 0

1

In [52]:
print(list)

[]


In [53]:
list.append(1)
list.append(2)
list.append(3)
list.append(4)
list.append(5)
list.append(6)
list.append(7)
list.append(8)
list.append(9)
list.append(9)

In [54]:
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 9]


In [55]:
list.remove(9) #remove only one 9 from the list

In [56]:
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [69]:
n=input("Enter the list item seperated with only one space:")
list2=n.split()
print(list2)



['1', '0', '5', '2', '5', '8', '8', '8', '88', '8', '8', '5', '5']


In [86]:
size=len(list2)
print(size)

13


In [85]:
for i in range(size):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12


In [87]:
print(list2)

['1', '0', '5', '2', '5', '8', '8', '8', '88', '8', '8', '5', '5']


In [90]:
while list2:
    print(list2.pop())

# for item in list2:
#     print(item)
# list2[:] = []

In [91]:
print(list2)

[]


proble solving questions


In [98]:
def creating_gen(index):  
    months = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']  
    yield months[index]  
    yield months[index+1]  
    yield months[index+2]  
next_month = creating_gen(0)  
print(next(next_month), next(next_month), next(next_month)) 

jan feb mar


Changing a list into a tuple

In [99]:
month = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']  
m_to_list = tuple(month)  # this will chage a list into a tuple
print(m_to_list)  
print(type(m_to_list))  


('jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec')
<class 'tuple'>


# what is numpy array
it is more versatile than the list

In [101]:
# creating an empty array in python

In [102]:
import numpy  
#method 1  
array_1 = numpy.array([])  
print(array_1)  
#method 2  
array_2 = numpy.empty(shape=(3,3))  
print(array_2)  

[]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.94457559e-321]
 [6.23053614e-307 7.56592337e-307 5.33590898e-322]]


In [103]:

a = [4, 6, 8, 3, 1, 7]  
print(a[-3])  
print(a[-5])  
print(a[-1])  

3
6
7


In [2]:
x=[] #blank list
x1=[1,2,3] # list with 3 element
x2=[4,5,'Apple','Orange'] # mixed element
x3=['Aman','Naman'] # string element

In [5]:
print(x, x1, x2, x3)

[] [1, 2, 3] [4, 5, 'Apple', 'Orange'] ['Aman', 'Naman']


In [7]:
x1 + x2 # adding two list 

[1, 2, 3, 4, 5, 'Apple', 'Orange']

In [8]:
x5 = x1*5
print(x5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [11]:
good_movies=['Pathan', '3 idiots', 'Bahubali', 'Farzi','Kabir Singh']
bad_movies=['Disaster','Birdemic','House of the dead', "son of the mask", 'circus']


In [12]:
all_movies= good_movies + bad_movies
print(all_movies)

['Pathan', '3 idiots', 'Bahubali', 'Farzi', 'Kabir Singh', 'Disaster', 'Birdemic', 'House of the dead', 'son of the mask', 'circus']


In [13]:
all_movies.append('Troll 2')
all_movies.append('The Conjuring')

In [15]:
print(all_movies)

['Pathan', '3 idiots', 'Bahubali', 'Farzi', 'Kabir Singh', 'Disaster', 'Birdemic', 'House of the dead', 'son of the mask', 'circus', 'Troll 2', 'The Conjuring']


In [16]:
print(len(all_movies))

12


In [17]:
all_movies.insert(2,'The Dark Knight')
print(all_movies)

['Pathan', '3 idiots', 'The Dark Knight', 'Bahubali', 'Farzi', 'Kabir Singh', 'Disaster', 'Birdemic', 'House of the dead', 'son of the mask', 'circus', 'Troll 2', 'The Conjuring']


In [18]:
sequels =['Fast & Furious', '2 fast 2 furious', 'Fast & Furious: Tokyo Draft']
all_movies.extend(sequels) # add all items of list 2 in list 1

In [19]:
print(all_movies)

['Pathan', '3 idiots', 'The Dark Knight', 'Bahubali', 'Farzi', 'Kabir Singh', 'Disaster', 'Birdemic', 'House of the dead', 'son of the mask', 'circus', 'Troll 2', 'The Conjuring', 'Fast & Furious', '2 fast 2 furious', 'Fast & Furious: Tokyo Draft']


In [20]:
print(len(all_movies))

16


In [24]:
all_movies.remove("Birdemic")


In [25]:
print(all_movies)

['Pathan', '3 idiots', 'The Dark Knight', 'Bahubali', 'Farzi', 'Kabir Singh', 'Disaster', 'House of the dead', 'circus', 'Troll 2', 'The Conjuring', 'Fast & Furious', '2 fast 2 furious', 'Fast & Furious: Tokyo Draft']


In [31]:
all_movies.sort


<function list.sort(*, key=None, reverse=False)>

In [38]:
all_movies[:5] # first five element

['2 fast 2 furious', '3 idiots', 'Bahubali', 'Disaster', 'Farzi']

In [40]:
all_movies[-5:] # last five element

['Pathan', 'The Conjuring', 'The Dark Knight', 'Troll 2', 'circus']

In [51]:
all_movies[3]= 'Bahubali 2 : The Conclusion'
print(all_movies)

['2 fast 2 furious', '3 idiots', 'Bahubali', 'Bahubali 2 : The Conclusion', 'Farzi', 'Fast & Furious', 'Fast & Furious: Tokyo Draft', 'House of the dead', 'Kabir Singh', 'Pathan', 'The Conjuring', 'The Dark Knight', 'Troll 2', 'circus']


In [50]:
all_movies.reverse
print(all_movies)

['2 fast 2 furious', '3 idiots', 'Bahubali', 'Bahubali 2 : The Conclusion', 'Farzi', 'Fast & Furious', 'Fast & Furious: Tokyo Draft', 'House of the dead', 'Kabir Singh', 'Pathan', 'The Conjuring', 'The Dark Knight', 'Troll 2', 'circus']


In [52]:
all_movies.sort()
print(all_movies)

['2 fast 2 furious', '3 idiots', 'Bahubali', 'Bahubali 2 : The Conclusion', 'Farzi', 'Fast & Furious', 'Fast & Furious: Tokyo Draft', 'House of the dead', 'Kabir Singh', 'Pathan', 'The Conjuring', 'The Dark Knight', 'Troll 2', 'circus']


In [53]:
all_movies.sort(reverse=True)
print(all_movies)

['circus', 'Troll 2', 'The Dark Knight', 'The Conjuring', 'Pathan', 'Kabir Singh', 'House of the dead', 'Fast & Furious: Tokyo Draft', 'Fast & Furious', 'Farzi', 'Bahubali 2 : The Conclusion', 'Bahubali', '3 idiots', '2 fast 2 furious']


In [55]:
import random as rnd
rnd.shuffle(all_movies)     
print(all_movies)

['Fast & Furious: Tokyo Draft', 'Pathan', 'The Dark Knight', 'Kabir Singh', 'Troll 2', 'Bahubali 2 : The Conclusion', '3 idiots', 'Farzi', '2 fast 2 furious', 'House of the dead', 'Bahubali', 'Fast & Furious', 'The Conjuring', 'circus']


In [60]:
rnd.choice(all_movies)

'circus'

In [69]:
rnd.choices(all_movies, k=2)

['Troll 2', 'Fast & Furious']

In [70]:
all_movies.index('3 idiots')

6

In [72]:
all_movies.pop() # remove element from last 

'The Conjuring'

In [73]:
all_movies.pop(3) # remove element at that index

'Kabir Singh'

In [77]:
x= [1,2,3,4]
y = x
y[0]=100 # here the changes will happen in both x and y
x[2]= 200
print(x)
print(y)
print(x is y)
print(y is x)

[100, 2, 200, 4]
[100, 2, 200, 4]
True
True


In [78]:
z = x.copy() # this will copy the value of x in z
z.pop()
print(x)
print(z)

[100, 2, 200, 4]
[100, 2, 200]


In [79]:
print(z is x)

False
